export const browserCoreExamples = [
  "logica browser status",
  "logica browser start",
  "logica browser stop",
  "logica browser tabs",
  "logica browser open https://example.com",
  "logica browser focus abcd1234",
  "logica browser close abcd1234",
  "logica browser screenshot",
  "logica browser screenshot --full-page",
  "logica browser screenshot --ref 12",
  "logica browser snapshot",
  "logica browser snapshot --format aria --limit 200",
  "logica browser snapshot --efficient",
  "logica browser snapshot --labels",
];

export const browserActionExamples = [
  "logica browser navigate https://example.com",
  "logica browser resize 1280 720",
  "logica browser click 12 --double",
  'logica browser type 23 "hello" --submit',
  "logica browser press Enter",
  "logica browser hover 44",
  "logica browser drag 10 11",
  "logica browser select 9 OptionA OptionB",
  "logica browser upload /tmp/file.pdf",
  'logica browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "logica browser dialog --accept",
  'logica browser wait --text "Done"',
  "logica browser evaluate --fn '(el) => el.textContent' --ref 7",
  "logica browser console --level error",
  "logica browser pdf",
];
